/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens;

import D02_ThucThi.LoginRun;
import D02_ThucThi.QuanLySP;
import static Screens.Main.choice;
import static Screens.Main.dfTableHD;
import static Screens.Main.dfTableKH;
import static Screens.Main.dfTableSP;
import static Screens.Main.qlcthd;
import static Screens.Main.qlhd;
import static Screens.Main.qlkh;
import static Screens.Main.qlnv;
import static Screens.Main.qlsp;
import static Screens.Main.screenIsOn;
import static Screens.Main.taittcthd;
import static Screens.Main.taitthd;
import static Screens.Main.taittkh;
import static Screens.Main.taittsp;
import static Screens.NhapTTHD.tempTableSP;
import static Screens.NhapTTHD.tinhTriGia;
import static Screens.NhapTTHD.trigia;
import doancuoiky.DoAnCuoiKy;
import static doancuoiky.DoAnCuoiKy.setRightRendererAndResizeWitdh;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class BanHangChoNV extends javax.swing.JFrame {

    public static String maKH;
    static String maKH1;
    static boolean checkMaKH = false, confirm = false, buttonThemSPIsActive = false, buttonCapNhatSPIsActive = false, buttonXoaSPIsActive = false, buttonXoaKHIsActive = false, buttonCapNhatKHIsActive = false;

    /**
     * Creates new form BanHangChoNV
     */
    public BanHangChoNV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtHoTenNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgayTaoHD = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        buttonThanhToan = new javax.swing.JButton();
        buttonHuy = new javax.swing.JButton();
        txtMaKH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableListSP_staff = new javax.swing.JTable();
        txtThongTinSP = new javax.swing.JTextField();
        comboBoxMaSP = new javax.swing.JComboBox<>();
        txtSL = new javax.swing.JTextField();
        buttonThemSP = new javax.swing.JButton();
        buttonXoaSP = new javax.swing.JButton();
        txtTongTien = new javax.swing.JTextField();
        txtSinhNhatKH = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtLoaiKH = new javax.swing.JTextField();
        txtSoHD = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonTaiTTKH = new javax.swing.JButton();
        butonCapNhatKH = new javax.swing.JButton();
        buttonXoaKH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKhachHang = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        timKiemComboBox = new javax.swing.JComboBox<>();
        txtMa = new javax.swing.JTextField();
        buttonTim = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buttonThemSP_TBHD = new javax.swing.JButton();
        buttonCapNhatSP = new javax.swing.JButton();
        buttonXoaSP_TBHD = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        timKiemComboBox1 = new javax.swing.JComboBox<>();
        txtMaSP = new javax.swing.JTextField();
        buttonTim1 = new javax.swing.JButton();
        buttonTaiTTSP = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        buttonXemCTHD = new javax.swing.JButton();
        buttonXoaHD = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableHoaDon = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        timKiemComboBox2 = new javax.swing.JComboBox<>();
        txtMaHD = new javax.swing.JTextField();
        buttonTim2 = new javax.swing.JButton();
        buttonTaiTTHD = new javax.swing.JButton();
        buttonDangXuat = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("ỨNG DỤNG QUẢN LÝ BÁN HÀNG");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("THÊM MỚI HÓA ĐƠN SỐ");

        txtHoTenNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHoTenNV.setText("HO TEN NV");

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaNV.setText("MANV");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Thông tin sản phẩm");

        txtNgayTaoHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNgayTaoHD.setText("NGAY LAP DON");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Mã SP");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Số lượng");

        buttonThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonThanhToan.setText("Thanh toán");
        buttonThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThanhToanActionPerformed(evt);
            }
        });

        buttonHuy.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonHuy.setText("Hủy");
        buttonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHuyActionPerformed(evt);
            }
        });

        txtMaKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaKH.setToolTipText("Nhập MAKH hoặc SĐT");
        txtMaKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaKHKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel10.setText("Tổng tiền");

        tableListSP_staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "ĐVT", "Xuất xứ", "Giá", "SL", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableListSP_staff);

        txtThongTinSP.setEditable(false);
        txtThongTinSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        comboBoxMaSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBoxMaSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxMaSP.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboBoxMaSPPopupMenuWillBecomeVisible(evt);
            }
        });
        comboBoxMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMaSPActionPerformed(evt);
            }
        });

        txtSL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonThemSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonThemSP.setText("Thêm SP");
        buttonThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemSPActionPerformed(evt);
            }
        });

        buttonXoaSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonXoaSP.setText("Xóa SP");
        buttonXoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaSPActionPerformed(evt);
            }
        });

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N

        txtSinhNhatKH.setEditable(false);
        txtSinhNhatKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSinhNhatKH.setText("SINH NHAT");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Sinh nhật");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Loại KH");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Khách hàng");

        txtLoaiKH.setEditable(false);
        txtLoaiKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLoaiKH.setText("LOAI KH");

        txtSoHD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtSoHD.setText("SOHD");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel3.setText("VNĐ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThongTinSP)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonThemSP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonXoaSP))
                            .addComponent(jLabel9))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSinhNhatKH, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHoTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSoHD)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNgayTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(16, 16, 16)
                                .addComponent(buttonThanhToan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonHuy)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaNV)
                            .addComponent(txtHoTenNV))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSoHD))
                        .addGap(14, 14, 14)
                        .addComponent(txtNgayTaoHD)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtSinhNhatKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThongTinSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonThemSP)
                    .addComponent(buttonXoaSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonThanhToan)
                    .addComponent(buttonHuy)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tạo hóa đơn mới", jPanel1);

        buttonTaiTTKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonTaiTTKH.setText("TẢI TT KHÁCH HÀNG");
        buttonTaiTTKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTaiTTKHActionPerformed(evt);
            }
        });

        butonCapNhatKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        butonCapNhatKH.setText("CẬP NHẬT TT KHÁCH HÀNG");
        butonCapNhatKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonCapNhatKHActionPerformed(evt);
            }
        });

        buttonXoaKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonXoaKH.setText("XÓA KHÁCH HÀNG");
        buttonXoaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaKHActionPerformed(evt);
            }
        });

        tableKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KH", "Họ và tên", "Địa chỉ", "Số ĐT", "Sinh nhật", "Ngày ĐK", "Doanh số", "Loại KH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableKhachHang.setDropMode(javax.swing.DropMode.ON);
        tableKhachHang.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableKhachHang.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableKhachHang);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Tìm kiếm nhanh theo ");

        timKiemComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timKiemComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtMa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        buttonTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonTim.setText("Tìm");
        buttonTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buttonTaiTTKH)
                .addGap(68, 68, 68)
                .addComponent(butonCapNhatKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(buttonXoaKH)
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timKiemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonTim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTim)
                    .addComponent(timKiemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTaiTTKH)
                    .addComponent(butonCapNhatKH)
                    .addComponent(buttonXoaKH))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý khách hàng", jPanel2);

        buttonThemSP_TBHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonThemSP_TBHD.setText("THÊM SẢN PHẨM");
        buttonThemSP_TBHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemSP_TBHDActionPerformed(evt);
            }
        });

        buttonCapNhatSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonCapNhatSP.setText("CẬP NHẬT SẢN PHẨM");
        buttonCapNhatSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCapNhatSPActionPerformed(evt);
            }
        });

        buttonXoaSP_TBHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonXoaSP_TBHD.setText("XÓA SẢN PHẨM");
        buttonXoaSP_TBHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaSP_TBHDActionPerformed(evt);
            }
        });

        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Đơn vị tính", "Nước sản xuất", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSanPham.setDropMode(javax.swing.DropMode.ON);
        tableSanPham.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableSanPham.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tableSanPham);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tìm kiếm nhanh theo ");

        timKiemComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timKiemComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtMaSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        buttonTim1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonTim1.setText("Tìm");
        buttonTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTim1ActionPerformed(evt);
            }
        });

        buttonTaiTTSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonTaiTTSP.setText("TẢI TT SP");
        buttonTaiTTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTaiTTSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timKiemComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonTim1)
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(buttonTaiTTSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonThemSP_TBHD)
                .addGap(36, 36, 36)
                .addComponent(buttonCapNhatSP)
                .addGap(26, 26, 26)
                .addComponent(buttonXoaSP_TBHD)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTim1)
                    .addComponent(timKiemComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonThemSP_TBHD)
                    .addComponent(buttonCapNhatSP)
                    .addComponent(buttonXoaSP_TBHD)
                    .addComponent(buttonTaiTTSP))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý sản phẩm", jPanel3);

        buttonXemCTHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonXemCTHD.setText("XEM CHI TIẾT HÓA ĐƠN");
        buttonXemCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXemCTHDActionPerformed(evt);
            }
        });

        buttonXoaHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonXoaHD.setText("XÓA HÓA ĐƠN");
        buttonXoaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaHDActionPerformed(evt);
            }
        });

        tableHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Số HD", "Ngày Lập", "Mã Khách Hàng", "Mã Nhân Viên", "Trị Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHoaDon.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(tableHoaDon);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Tìm kiếm nhanh theo ");

        timKiemComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timKiemComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtMaHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        buttonTim2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonTim2.setText("Tìm");
        buttonTim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTim2ActionPerformed(evt);
            }
        });

        buttonTaiTTHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonTaiTTHD.setText("TẢI TT HÓA ĐƠN");
        buttonTaiTTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTaiTTHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(buttonTaiTTHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonXemCTHD)
                .addGap(112, 112, 112)
                .addComponent(buttonXoaHD)
                .addGap(68, 68, 68))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timKiemComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonTim2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTim2)
                    .addComponent(timKiemComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonXemCTHD)
                    .addComponent(buttonXoaHD)
                    .addComponent(buttonTaiTTHD))
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Quản lý hóa đơn", jPanel4);

        buttonDangXuat.setText("Đăng xuất");
        buttonDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(160, 160, 160)
                .addComponent(buttonDangXuat)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDangXuat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDangXuatActionPerformed
        // TODO add your handling code here:
        Login.statusLogin = false;
        Main.disposeAll();
        Login frmLogin = new Login();
        frmLogin.setLocationRelativeTo(null);
        frmLogin.setVisible(true);
    }//GEN-LAST:event_buttonDangXuatActionPerformed

    public static void setScreen() {
        txtMaKH.setText(maKH + " - " + qlkh.getTenKH(maKH));
        txtSinhNhatKH.setText(qlkh.getSinhNhat(maKH));
        txtLoaiKH.setText(qlkh.getLoaiKH(maKH));
        checkMaKH = true;
    }

    private void themKH() {
        int choice = JOptionPane.showConfirmDialog(null, "Mã KH không đúng hoặc không tồn tại. Bạn có muốn tạo KH mới?", "Thông báo", 0);
        if (choice == 0 && !screenIsOn) {
            NhapTTKH nhapttkh = new NhapTTKH();
            nhapttkh.setLocationRelativeTo(null);
            nhapttkh.setVisible(true);
            nhapttkh.maKh.setText(new DoAnCuoiKy().tangMa(qlkh.getMaCuoi()));
            nhapttkh.ngdk.setText(new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime()));
            screenIsOn = true;
        }
    }

    private void themKHTheoSDT(String sdt) {
        int choice = JOptionPane.showConfirmDialog(null, "Không tìm thấy thông tin SĐT này. Bạn có muốn tạo KH mới?", "Thông báo", 0);
        if (choice == 0 && !screenIsOn) {
            NhapTTKH nhapttkh = new NhapTTKH();
            nhapttkh.setLocationRelativeTo(null);
            nhapttkh.setVisible(true);
            nhapttkh.maKh.setText(new DoAnCuoiKy().tangMa(qlkh.getMaCuoi()));
            nhapttkh.ngdk.setText(new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime()));
            nhapttkh.txtSoDTKH.setText(sdt);
            screenIsOn = true;
        }
    }

    private void mouseClick() {
        if (!txtMaKH.getText().isBlank() && !checkMaKH) {
            if (txtMaKH.getText().length() == 4) {
                maKH = txtMaKH.getText().toUpperCase();
                if (qlkh.checkMaKH(maKH)) {
                    setScreen();
                } else {
                    themKH();
                }
            } else if (txtMaKH.getText().length() >= 8 && txtMaKH.getText().length() <= 11) {
                if (qlkh.checkSDTKH(txtMaKH.getText()) != null) {
                    maKH = qlkh.checkSDTKH(txtMaKH.getText());
                    setScreen();
                } else {
                    themKHTheoSDT(txtMaKH.getText());
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Độ dài mã KH hoặc số ĐT không đúng. Hãy nhập lại.");
            }
        }
        checkMaKH = true;
    }

    public void tim(javax.swing.JTable table, String maTimKiem, int loaiTK) {
        for (int i = 0; i < table.getRowCount(); i++) {
            if (table.getValueAt(i, loaiTK).toString().equalsIgnoreCase(maTimKiem)) {
                JOptionPane.showMessageDialog(null, "Đã tìm thấy !!!");
                table.setRowSelectionInterval(i, i);
                table.scrollRectToVisible(table.getCellRect(i, 2, true));
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Không tìm thấy dữ liệu có mã " + txtMa.getText() + "\nVui lòng kiểm tra lại thông tin tìm kiếm!!!");
    }

    private void txtMaKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaKHKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtMaKH.getText().length() == 4) {
                maKH = txtMaKH.getText().toUpperCase();
                if (qlkh.checkMaKH(maKH)) {
                    setScreen();
                } else {
                    themKH();
                    checkMaKH = true;
                }
            } else if (txtMaKH.getText().length() >= 8 && txtMaKH.getText().length() <= 11) {
                if (qlkh.checkSDTKH(txtMaKH.getText()) != null) {
                    maKH = qlkh.checkSDTKH(txtMaKH.getText());
                    setScreen();
                } else {
                    themKHTheoSDT(txtMaKH.getText());
                    maKH = qlkh.getMaCuoi();
                    setScreen();
                    checkMaKH = true;
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Độ dài mã KH hoặc số ĐT không đúng. Hãy nhập lại.");
            }
        }
    }//GEN-LAST:event_txtMaKHKeyPressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        mouseClick();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void comboBoxMaSPPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboBoxMaSPPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        mouseClick();
    }//GEN-LAST:event_comboBoxMaSPPopupMenuWillBecomeVisible

    private void comboBoxMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMaSPActionPerformed
        // TODO add your handling code here:
        String maSP = comboBoxMaSP.getSelectedItem().toString();
        txtThongTinSP.setText(qlsp.getTTSP(maSP));
    }//GEN-LAST:event_comboBoxMaSPActionPerformed

    private void buttonThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemSPActionPerformed

        if (comboBoxMaSP.getSelectedItem() == null || txtSL.getText().isBlank() || Integer.parseInt(txtSL.getText()) <= 0)
            JOptionPane.showMessageDialog(null, "Hay nhap dung ma san pham va so luong!!!");
        else {
            int soluong = Integer.parseInt(txtSL.getText());
            String maSp = comboBoxMaSP.getSelectedItem().toString();
            trigia += tinhTriGia(maSp, soluong);
            txtTongTien.setText(String.format("%,d", (trigia)));
            txtTongTien.setHorizontalAlignment(JTextField.RIGHT);
            txtTongTien.setVisible(true);
            QuanLySP.getSP(maSp, soluong, tempTableSP);
            tableListSP_staff.setModel(tempTableSP);
            DoAnCuoiKy.setRightRendererAndResizeWitdh(tableListSP_staff);
        }
    }//GEN-LAST:event_buttonThemSPActionPerformed

    private void buttonXoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaSPActionPerformed
        // TODO add your handling code here:
        int i = tableListSP_staff.getSelectedRow();
        if (i >= 0 && tableListSP_staff.getRowCount() > 0) {
            int choice = JOptionPane.showConfirmDialog(null, "Ban co chac chan muon xoa du lieu nay", "Thong bao", 0);
            if (choice == 0) {
                trigia -= (Long.parseLong((String) tableListSP_staff.getValueAt(i, 5)) * qlsp.getGia((String) tableListSP_staff.getValueAt(i, 0)));
                txtTongTien.setText(String.format("%,d", (trigia)));
                txtTongTien.setHorizontalAlignment(JTextField.RIGHT);
                tempTableSP.removeRow(i);
                tableListSP_staff.setModel(tempTableSP);
                setRightRendererAndResizeWitdh(tableListSP_staff);
            }
        }
    }//GEN-LAST:event_buttonXoaSPActionPerformed

    private void buttonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHuyActionPerformed
        // TODO add your handling code here:
        dispose();
//        setVisible(false);
        tempTableSP = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        LoginRun.getStaffScreens();
        screenIsOn = false;
    }//GEN-LAST:event_buttonHuyActionPerformed

    private void buttonThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThanhToanActionPerformed
        // TODO add your handling code here:
        if (trigia == 0 || txtMaKH.getText().isBlank() || tableListSP_staff.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Hay nhap du thong tin cua hoa don truoc khi tao!!!");
        } else if (!qlkh.checkMaKH(maKH)) {
            int choice = JOptionPane.showConfirmDialog(null, "Thông tin KH không đúng hoặc không tồn tại. Bạn có muốn tạo KH mới?", "Thông báo", 0);
            if (choice == 0 && !screenIsOn) {
                NhapTTKH nhapttkh = new NhapTTKH();
                nhapttkh.setLocationRelativeTo(null);
                nhapttkh.setVisible(true);
                nhapttkh.maKh.setText(new DoAnCuoiKy().tangMa(qlkh.getMaCuoi()));
                nhapttkh.ngdk.setText(new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime()));
                screenIsOn = true;
            }
        } else {
            boolean check = qlhd.themHD(txtSoHD.getText(), Calendar.getInstance().getTime(), maKH, Login.txtUser.getText().toUpperCase(), trigia);
            if (check) {
                JOptionPane.showMessageDialog(null, "Tạo thành công!!! Số hóa đơn: " + txtSoHD.getText());
                for (int i = 0; i < tableListSP_staff.getRowCount(); i++) {
                    qlcthd.themCTTD(txtSoHD.getText(), (String) tableListSP_staff.getValueAt(i, 0), (String) tableListSP_staff.getValueAt(i, 5));
                }
                Main.dfTableCTHD = qlcthd.taiTT();
                qlkh.capNhatDS(maKH, trigia);
                Main.countButtonXoaHD = 1;
                dispose();
                tempTableSP = new DefaultTableModel() {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        //all cells false
                        return false;
                    }
                };
                LoginRun.getStaffScreens();
            } else {
                JOptionPane.showMessageDialog(null, "Tạo HD không thành công, vui lòng kiểm tra lại");
            }
        }
    }//GEN-LAST:event_buttonThanhToanActionPerformed

    private void butonCapNhatKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonCapNhatKHActionPerformed
        System.out.println(choice);
        if (tableKhachHang.getSelectedRow() >= 0 && taittkh && !screenIsOn) {
            ManHinhXacNhan xacNhan = new ManHinhXacNhan();
            xacNhan.setVisible(true);
            xacNhan.setLocationRelativeTo(null);
            buttonCapNhatKHIsActive = true;
            screenIsOn = true;
        }
        toBack();
        if (!screenIsOn && choice != 1)
            JOptionPane.showMessageDialog(rootPane, "Click chọn dòng để thực hiện");
    }//GEN-LAST:event_butonCapNhatKHActionPerformed

    private void buttonTaiTTKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTaiTTKHActionPerformed
        // TODO add your handling code here:
        toBack();
        choice = 3;
        dfTableKH = qlkh.taiTT();
        tableKhachHang.setModel(dfTableKH);
        setRightRendererAndResizeWitdh(tableKhachHang);
    }//GEN-LAST:event_buttonTaiTTKHActionPerformed

    private void buttonXoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaKHActionPerformed
        if (tableKhachHang.getSelectedRow() >= 0 && taittkh && !screenIsOn) {
            maKH1 = tableKhachHang.getValueAt(tableKhachHang.getSelectedRow(), 1).toString();
            ManHinhXacNhan xacNhan = new ManHinhXacNhan();
            xacNhan.setVisible(true);
            xacNhan.setLocationRelativeTo(null);
            buttonXoaKHIsActive = true;
            screenIsOn = true;
        }
        toBack();
        if (!screenIsOn && choice != 1)
            JOptionPane.showMessageDialog(rootPane, "Click chọn dòng để thực hiện");
    }//GEN-LAST:event_buttonXoaKHActionPerformed

    private void buttonTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTimActionPerformed
        if (txtMa.getText().isBlank() || timKiemComboBox.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập đầy đủ thông tin để tìm kiếm");
        else {
            String maTimKiem = txtMa.getText();
            int loaiTK = timKiemComboBox.getSelectedIndex();
            tim(tableKhachHang, maTimKiem, loaiTK);

        }
    }//GEN-LAST:event_buttonTimActionPerformed

    private void buttonTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTim1ActionPerformed
        if (txtMaSP.getText().isBlank() || timKiemComboBox1.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập đầy đủ thông tin để tìm kiếm");
        else {
            String maTimKiem = txtMaSP.getText();
            int loaiTK = timKiemComboBox1.getSelectedIndex();
            tim(tableSanPham, maTimKiem, loaiTK);
        }
    }//GEN-LAST:event_buttonTim1ActionPerformed

    private void buttonTim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTim2ActionPerformed
        if (txtMaHD.getText().isBlank() || timKiemComboBox2.getSelectedIndex() == -1)
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập đầy đủ thông tin để tìm kiếm");
        else {
            String maTimKiem = txtMaHD.getText();
            int loaiTK = timKiemComboBox2.getSelectedIndex();
            tim(tableHoaDon, maTimKiem, loaiTK);
        }
    }//GEN-LAST:event_buttonTim2ActionPerformed

    private void buttonThemSP_TBHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemSP_TBHDActionPerformed
        if (tableSanPham.getSelectedRow() >= 0 && taittsp && !screenIsOn) {
            ManHinhXacNhan xacNhan = new ManHinhXacNhan();
            xacNhan.setVisible(true);
            xacNhan.setLocationRelativeTo(null);
            buttonThemSPIsActive = true;
            screenIsOn = true;
        }
        toBack();
    }//GEN-LAST:event_buttonThemSP_TBHDActionPerformed

    private void buttonCapNhatSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCapNhatSPActionPerformed
        if (tableSanPham.getSelectedRow() >= 0 && taittsp && !screenIsOn) {
            ManHinhXacNhan xacNhan = new ManHinhXacNhan();
            xacNhan.setVisible(true);
            xacNhan.setLocationRelativeTo(null);
            buttonCapNhatSPIsActive = true;
            screenIsOn = true;
        }
        toBack();
        if (!screenIsOn && choice != 1)
            JOptionPane.showMessageDialog(rootPane, "Click chọn dòng để thực hiện");
    }//GEN-LAST:event_buttonCapNhatSPActionPerformed

    private void buttonXoaSP_TBHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaSP_TBHDActionPerformed
        if (tableSanPham.getSelectedRow() >= 0 && taittsp && !screenIsOn) {
            ManHinhXacNhan xacNhan = new ManHinhXacNhan();
            xacNhan.setVisible(true);
            xacNhan.setLocationRelativeTo(null);
            buttonXoaSPIsActive = true;
            screenIsOn = true;
        }
        toBack();
        if (!screenIsOn && choice != 1)
            JOptionPane.showMessageDialog(rootPane, "Click chọn dòng để thực hiện");
    }//GEN-LAST:event_buttonXoaSP_TBHDActionPerformed

    private void buttonXemCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXemCTHDActionPerformed
        int i = tableHoaDon.getSelectedRow();
        if (i >= 0 && taitthd && !screenIsOn) {
            CapNhatTTHD capnhattthd = new CapNhatTTHD();
            String mahd = tableHoaDon.getValueAt(i, 1).toString();
            DefaultTableModel tableCT = qlcthd.getCTTheoHD(mahd);
            CapNhatTTHD.tableCTHD.setModel(tableCT);
            setRightRendererAndResizeWitdh(CapNhatTTHD.tableCTHD);
            taittcthd = true;
            CapNhatTTHD.txtsoHD.setText("CHI TIẾT HÓA ĐƠN : " + tableHoaDon.getValueAt(i, 1).toString());
            String maNV = tableHoaDon.getValueAt(i, 4).toString(), maKH5 = tableHoaDon.getValueAt(i, 3).toString();
            CapNhatTTHD.txtNV.setText(maNV + " - " + qlnv.getTenNV(maNV));
            CapNhatTTHD.txtKH.setText(maKH5 + " - " + qlkh.getTenKH(maKH5));
            CapNhatTTHD.txtNgHD.setText("Ngày lập: " + tableHoaDon.getValueAt(i, 2).toString());
            capnhattthd.setLocationRelativeTo(null);
            capnhattthd.setVisible(true);
            screenIsOn = true;
        }
        toBack();
        if (!screenIsOn && choice != 1)
            JOptionPane.showMessageDialog(rootPane, "Click chọn dòng để thực hiện");
    }//GEN-LAST:event_buttonXemCTHDActionPerformed

    private void buttonXoaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaHDActionPerformed
        if (tableHoaDon.getSelectedRow() >= 0 && taitthd && !screenIsOn) {
            ManHinhXacNhan xacNhan = new ManHinhXacNhan();
            xacNhan.setVisible(true);
            xacNhan.setLocationRelativeTo(null);
            screenIsOn = true;
        }
        toBack();
        if (!screenIsOn && choice != 1)
            JOptionPane.showMessageDialog(rootPane, "Click chọn dòng để thực hiện");
    }//GEN-LAST:event_buttonXoaHDActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex() != 0) {
            DefaultComboBoxModel comboModels = new DefaultComboBoxModel();
            switch (jTabbedPane1.getSelectedIndex()) {
                case 1 -> {
                    Main.setComboBoxInfo(tableKhachHang, comboModels);
                    timKiemComboBox.setModel(comboModels);
                    timKiemComboBox.setSelectedIndex(0);
                }
                case 2 -> {
                    Main.setComboBoxInfo(BanHangChoNV.tableSanPham, comboModels);
                    timKiemComboBox1.setModel(comboModels);
                    timKiemComboBox1.setSelectedIndex(0);
                }
                case 3 -> {
                    Main.setComboBoxInfo(BanHangChoNV.tableHoaDon, comboModels);
                    timKiemComboBox2.setModel(comboModels);
                    timKiemComboBox2.setSelectedIndex(0);
                }
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void buttonTaiTTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTaiTTSPActionPerformed
        toBack();
        choice = 3;
        dfTableSP = qlsp.taiTT();
        tableSanPham.setModel(dfTableSP);
        setRightRendererAndResizeWitdh(tableSanPham);
    }//GEN-LAST:event_buttonTaiTTSPActionPerformed

    private void buttonTaiTTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTaiTTHDActionPerformed
        toBack();
        choice = 3;
        dfTableHD = qlhd.taiTTTheoMaNV(Login.txtUser.getText().toUpperCase());
        tableHoaDon.setModel(dfTableHD);
        setRightRendererAndResizeWitdh(tableHoaDon);
    }//GEN-LAST:event_buttonTaiTTHDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangChoNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BanHangChoNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonCapNhatKH;
    static javax.swing.JButton buttonCapNhatSP;
    private javax.swing.JButton buttonDangXuat;
    private javax.swing.JButton buttonHuy;
    private javax.swing.JButton buttonTaiTTHD;
    private javax.swing.JButton buttonTaiTTKH;
    private javax.swing.JButton buttonTaiTTSP;
    private javax.swing.JButton buttonThanhToan;
    private javax.swing.JButton buttonThemSP;
    static javax.swing.JButton buttonThemSP_TBHD;
    javax.swing.JButton buttonTim;
    javax.swing.JButton buttonTim1;
    javax.swing.JButton buttonTim2;
    private javax.swing.JButton buttonXemCTHD;
    static javax.swing.JButton buttonXoaHD;
    static javax.swing.JButton buttonXoaKH;
    private javax.swing.JButton buttonXoaSP;
    static javax.swing.JButton buttonXoaSP_TBHD;
    public static javax.swing.JComboBox<String> comboBoxMaSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    static javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable tableHoaDon;
    public static javax.swing.JTable tableKhachHang;
    public static javax.swing.JTable tableListSP_staff;
    public static javax.swing.JTable tableSanPham;
    static javax.swing.JComboBox<String> timKiemComboBox;
    static javax.swing.JComboBox<String> timKiemComboBox1;
    static javax.swing.JComboBox<String> timKiemComboBox2;
    public static javax.swing.JLabel txtHoTenNV;
    static javax.swing.JTextField txtLoaiKH;
    static javax.swing.JTextField txtMa;
    static javax.swing.JTextField txtMaHD;
    static javax.swing.JTextField txtMaKH;
    public static javax.swing.JLabel txtMaNV;
    static javax.swing.JTextField txtMaSP;
    public static javax.swing.JLabel txtNgayTaoHD;
    static javax.swing.JTextField txtSL;
    static javax.swing.JTextField txtSinhNhatKH;
    public static javax.swing.JLabel txtSoHD;
    static javax.swing.JTextField txtThongTinSP;
    static javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
