/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens;

import static Screens.BanHangChoNV.maKH1;
import static Screens.BanHangChoNV.tableHoaDon;
import static Screens.BanHangChoNV.tableKhachHang;
import static Screens.BanHangChoNV.tableSanPham;
import static Screens.Main.choice;
import static Screens.Main.countButtonXoaHD;
import static Screens.Main.countButtonXoaKH;
import static Screens.Main.countButtonXoaSP;
import static Screens.Main.dfTableCTHD;
import static Screens.Main.dfTableHD;
import static Screens.Main.dfTableKH;
import static Screens.Main.dfTableSP;
import static Screens.Main.maSR;
import static Screens.Main.qlcthd;
import static Screens.Main.qldn;
import static Screens.Main.qlhd;
import static Screens.Main.qlkh;
import static Screens.Main.qlsp;
import static Screens.Main.tableCTHD;
import static Screens.Main.taitthd;
import static Screens.Main.taittkh;
import static Screens.Main.taittsp;
import static doancuoiky.DoAnCuoiKy.setRightRendererAndResizeWitdh;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class ManHinhXacNhan extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhXacNhan
     */
    public ManHinhXacNhan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaBaoVe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Thông báo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Đây là thao tác nguy hiểm, hãy nhập mã bảo vệ để tiếp tục");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã bảo vệ: ");

        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(txtMaBaoVe))
                        .addGap(50, 50, 50))))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaBaoVe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (txtMaBaoVe.getText().equalsIgnoreCase(qldn.getMaBaoVe())) {
            switch (BanHangChoNV.jTabbedPane1.getSelectedIndex()) {
                case 1 -> {
                    setVisible(false);
                    if (Main.xoaAction(tableKhachHang, taittkh, countButtonXoaKH, BanHangChoNV.buttonXoaKH, dfTableKH, qlkh)) {
                        JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                        countButtonXoaKH++;
                        if (qlhd.check(maKH1)) {
                            qlhd.xoaDongTrenSQL(qlhd.laySoHDTheoMaKH(maSR));
                            dfTableHD = qlhd.taiTT();
                            tableHoaDon.setModel(dfTableHD);
                            setRightRendererAndResizeWitdh(tableHoaDon);
                            qlcthd.xoaDongTrenSQL(qlhd.laySoHDTheoMaKH(maSR));
                            dfTableCTHD = qlcthd.taiTT();
                            tableCTHD.setModel(dfTableCTHD);
                            setRightRendererAndResizeWitdh(tableCTHD);
                        }
                    } else {
                        if (choice == 0) {
                            JOptionPane.showMessageDialog(rootPane, "Không thành công.\nVui lòng kiểm tra lại");
                        }
                    }
                }
                case 2 -> {
                    setVisible(false);
                    if (Main.xoaAction(tableSanPham, taittsp, countButtonXoaSP, BanHangChoNV.buttonXoaSP_TBHD, dfTableSP, qlsp)) {
                        countButtonXoaSP++;
                        JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                    } else {
                        if (choice == 0) {
                            JOptionPane.showMessageDialog(rootPane, "Không thành công.\nVui lòng kiểm tra lại");
                        }
                    }
                }
                case 3 -> {
                    setVisible(false);
                    if (Main.xoaAction(tableHoaDon, taitthd, countButtonXoaHD, BanHangChoNV.buttonXoaHD, dfTableHD, qlhd)) {
                        JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                        countButtonXoaHD++;
                        qlcthd.xoaDongTrenSQL(maSR);
                        dfTableCTHD = qlcthd.taiTT();
                        tableCTHD.setModel(dfTableCTHD);
                        setRightRendererAndResizeWitdh(tableCTHD);
                        String maKh = qlhd.layMaKH(maSR);
                        long trigia = -qlhd.getTriGia(maSR);
                        qlkh.capNhatDS(maKh, trigia);
                        dfTableKH = qlkh.taiTT();
                        tableKhachHang.setModel(dfTableKH);
                        setRightRendererAndResizeWitdh(tableKhachHang);
                    } else {
                        if (choice == 0) {
                            JOptionPane.showMessageDialog(rootPane, "Không thành công.\nVui lòng kiểm tra lại");
                        }
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Sai mã bảo vệ, hủy thao tác");
            dispose();
            setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhXacNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhXacNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhXacNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhXacNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ManHinhXacNhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JTextField txtMaBaoVe;
    // End of variables declaration//GEN-END:variables
}
